### ISSUE TITLE
Bug: 大括号匹配不正确

### ISSUE THREAD

**Issue by Yixuan-Wang** [Guyutongxue/VSC_LalrpopHighlight#1]
![image](https://user-images.githubusercontent.com/21151119/157078772-73f72ab6-350f-405d-865a-d1096a9e494a.png)

Token & Scope 调试工具显示这两个括号配对到一起去了……下面这张图可能看得更清楚……

![image](https://user-images.githubusercontent.com/21151119/157079444-7545060b-0aae-4882-8c39-0f7533eea5e6.png)

**Comment by guyutongxue** [comment]
发布了新版本，以尝试修复此问题。tmLanguage 的表达能力很弱，我不认为我能覆盖到所有情况……但至少目前看上去还凑活。

如果新版本解决了你的问题的话，可以关闭此 issue。
