### ISSUE TITLE
Missing comment case?

### ISSUE THREAD

**Issue by Pat-Lafon** [Guyutongxue/VSC_LalrpopHighlight#3]
Hello, thanks for the extension!

I was writing a grammar and was initially unsure about how comments were handled because of the different syntax highlighting treatments. It doesn't look like comments before productions are noticed? See image below.

<img width="545" alt="image" src="https://github.com/Guyutongxue/VSC_LalrpopHighlight/assets/32135464/8ceb07df-7d0e-4b3c-a656-2a2a4ed5fd7f">

**Comment by guyutongxue** [comment]
Hello @Pat-Lafon, please try the latest version (0.0.5) and check if this issue is fixed.

**Comment by Pat-Lafon** [comment]
Wow that was fast! I updated to the latest version and it works as expected. Thanks!
